# Site settings
title: Zeeshan Minhas
tagline: Prestige Worldwide

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#263238"

# contact
author:
  name: Zeeshan Minhas
  url: http://github.com/zeeshanminhas

twitter_username: minhaszeeshan
github_username:  minhaszeeshan
github_url: "https://github.com/minhaszeeshan/minhas.xyz"

# Others
markdown: redcarpet

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
